export const options = [
  {
    Codigo_interno: "",
    Codigo_SAP: 1483390,
    SKU: "X",
    Descripcion: "CABLE UTP CAT5E MULTIFILAR LINKCHIP 300MT X CAJA",
    Stock: 7,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "X",
    Descripcion: "CABLE UTP CAT5E UNIFILAR DRAKA 300MT X CAJA",
    Stock: 10,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: 4103387,
    SKU: "X",
    Descripcion: "CABLE UTP CAT6 UNIFILAR TRIMERX 305MT X CAJA",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "X",
    Descripcion: "CABLE UTP CAT6 MULTIFILAR ECO 305MT X CAJA",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "CABLE UTP CAT6 NHTD UNIFILAR 305MT X CAJA",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: 4104736,
    SKU: "",
    Descripcion: "CABLE RADWIND 25MT X CAJA",
    Stock: 10,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: 4111682,
    SKU: "",
    Descripcion: "CABLE RADWIN 100MT X CAJA",
    Stock: 2,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: 4104736,
    SKU: "",
    Descripcion: "CABLE RADWIN 50MT X CAJA ",
    Stock: 15,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: 6415161,
    SKU: "",
    Descripcion: "CABECERA FO MURAL 24 HILOS CONECTOR FC / ST CON PLACA ACOPLADORA",
    Stock: 6,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "CABECERA FIBRA OPTICA 24 SC SC ",
    Stock: 40,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "LAP WIFI CISCO AP C9115AXI-A",
    Stock: 10,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "CABECERA FIBRA OPTICA 12",
    Stock: 2,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "MUFA FIBRA OPTICA 6 BANDEJAS 144F A8",
    Stock: 27,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "MUFA FIBRA OPTICA DOMO VERT 48F FOSC-DH01",
    Stock: 2,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "MUFA FIBRA OPTICA FOSC400 48A4",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "MUFA FIBRA OPTICA TIPO DOMO 48 HILOS",
    Stock: 2,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "ANTENA WIFI CISCO AIR AP1572EAC-A-K9",
    Stock: 2,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "TX ORDENADOR 19X2U HORIZONTAL TAPA SIMPLE",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "JUMPER FIBRA ST/FC SM 2MT",
    Stock: 54,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "JUMPER FIBRA ST/FC SM 3MT",
    Stock: 86,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "JUMPER FIBRA ST/FC SM 5MT",
    Stock: 5,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "JUMPER FIBRA ST/FC SM 6MT",
    Stock: 7,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  },
  {
    Codigo_interno: "",
    Codigo_SAP: null,
    SKU: "",
    Descripcion: "JUMPER FIBRA ST/FC SM 1MT",
    Stock: 1,
    Familia: "",
    Sub_Familia: "",
    Ubicacion: "NETWORKING",
    Comentarios: ""
  }
];
  